"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bz$n=e+&x44ghl3x7zel-zjyzp9k#neqzz)-7+shnvycv#pj&&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'authentication.apps.AuthenticationConfig',
    'tickets',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


import ldap
from django_auth_ldap.config import LDAPSearch, ActiveDirectoryGroupType

# 1. BACKENDS DE AUTENTICAÇÃO
AUTHENTICATION_BACKENDS = [
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# 2. CONFIGURAÇÃO DA CONEXÃO LDAP
AUTH_LDAP_SERVER_URI = os.getenv('LDAP_SERVER_URI'),
AUTH_LDAP_BIND_DN =  os.getenv('BIND_DN')
AUTH_LDAP_BIND_PASSWORD = os.getenv('BIND_PASSWORD')

# Configuração de conexão SSL que funcionou no script de teste
AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_X_TLS_NEWCTX: 0,
    ldap.OPT_X_TLS_REQUIRE_CERT: ldap.OPT_X_TLS_NEVER
}

# 3. CONFIGURAÇÃO DA BUSCA DE USUÁRIO
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    os.getenv('LDAP_SEARCH_USERS_BASE'),
    ldap.SCOPE_SUBTREE,
    "(sAMAccountName=%(user)s)"
)

# 4. MAPEAMENTO DE ATRIBUTOS E GRUPOS
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

# Configuração para dar permissão de acesso ao /admin para teste.
# Pode ser ajustado depois para um grupo específico.
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    
    # Apenas membros deste grupo específico terão acesso ao /admin
    #"is_staff": "CN=STAFF,CN=groups,DC=exemplo,DC=exemplo",
    
    # Você pode fazer o mesmo para superusuários
    #"is_superuser":"CN=ADMIN,OU=groups,DC=exemplo,DC=exemplo",
}

# (Opcional) Se quiser espelhar os grupos do AD para o Django
# settings.py

# Garanta que estas configurações estão ativas para que os grupos funcionem
AUTH_LDAP_MIRROR_GROUPS = True
AUTH_LDAP_FIND_GROUP_PERMS = True

# A configuração final e correta para a busca de grupos
from django_auth_ldap.config import LDAPSearch, ActiveDirectoryGroupType

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    os.getenv('LDAP_SEARCH_GROUP_BASE'),   # <-- O CAMINHO CORRETO E FINAL
    ldap.SCOPE_SUBTREE,
    "(objectClass=group)"
)

# Otimização para grupos do Active Directory
AUTH_LDAP_GROUP_TYPE = ActiveDirectoryGroupType()

AUTH_LDAP_MIRROR_GROUPS_EXCEPT = [
    'Domain Controllers',
    'Domain Admins',
    'Domain Computers',
    'Users',
    'Group Policy Creator Owners',
    'HelpDesk',
     
]


# 5. CONFIGURAÇÃO DE LOGGING PARA DEPURAÇÃO
import logging
logging.basicConfig(level=logging.DEBUG)
logging.getLogger('django_auth_ldap').setLevel(logging.DEBUG)